export {default as Home} from './home/Home'
export {default as Movies} from './movies/Movies'
export {default as Errorpage} from './error/Errorpage'
export {default as Footer} from './footer/Footer'
export {default as Moviepage} from './movie/Moviepage'
export {default as Login} from './login/Login'
export {default as Signup} from './signup/Signup'
export {default as Watchlistpage} from './watchlist/Watchlistpage';
export {default as Profile} from './profile/Profile';
export {default as Editprofile} from './editprofile/Editprofile';
export {default as Editfavourites} from './editprofile/Editfavourites';
